name: Update GVARs
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: modifed
      uses: jitterbit/get-changed-files@main
      with:
        format: 'json'
    - uses: 1drturtle/avrae-gvar-update-action@main
      with:
        avrae-token: '${{ secrets.AVRAETOKEN }}'
        gvar-ids-file: 'gvar-ids.json'
        modified-files: '${{ steps.modifed.outputs.added_modified }}'
